name: Deploy to Zeabur

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Zeabur CLI
        run: npm install -g @zeabur/cli

      - name: Deploy to Zeabur
        env:
          ZEB_TOKEN: ${{ secrets.ZEB_TOKEN }}
        run: zeabur deploy
        